apiVersion: batch/v1
kind: Job
metadata:
  name: restart-flagd
  namespace: astroshop
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: restart
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "pod", "-l", "app.kubernetes.io/component=flagd"]
      restartPolicy: Never