apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: astroshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: astroshop
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: astroshop
subjects:
- kind: ServiceAccount
  name: argocd
  namespace: astroshop
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io