#!/bin/bash

NAMESPACE="astroshop"

helm upgrade --install \
    --create-namespace \
    -n ${NAMESPACE} \
    --atomic \
    --debug \
    --post-renderer ./hook-ownership \
    --set collectorTenantToken="${DATA_INGEST_TOKEN}" \
    --set collectorTenantEndpoint="${OTEL_INGEST_ENDPOINT}" \
    astroshop ../../charts/astroshop