apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cart-state-store
  namespace: "{{ .Release.Namespace }}"
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: '{{ include "opentelemetry-demo.redisHost" . }}'
    - name: enableTLS
      value: false
