apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: app-config
  namespace: "{{ .Release.Namespace }}"
spec:
  metrics:
    enabled: true
    recordErrorCodes: true
  logging:
    apiLogging:
      enabled: true
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: {{ printf "%s:4317"  (index .Values "opentelemetry-demo" "opentelemetry-collector" "nameOverride") | quote }}
      isSecure: true
      protocol: grpc
