apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  {{- with (index .Values.opentelemetry-demo).components.postgresql.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
  {{- end }}
