apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
  labels:
    astroshop.org/owner: &name Team-Financial-Services
spec:
  template:
    metadata:
      labels:
        astroshop.org/owner: *name
