apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cart-state-store
  namespace: "{{ .Release.Namespace }}"

spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "{{ index .Values "opentelemetry-demo" "components" "valkey-cart" "ports" 0 "name" }}:{{ index .Values "opentelemetry-demo" "components" "valkey-cart" "ports" 0 "value" }}"
  - name: enableTLS
    value: false 