apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-otelcol-dt-api-credentials
type: Opaque
stringData:
  DT_ENDPOINT: "{{ .Values.default.collectorTenantEndpoint }}"
  DT_API_TOKEN: "{{ .Values.default.collectorTenantToken }}"
