name: Approve bot PR

on:
  pull_request:
    types:
      - opened
    paths:
      - flagd/**

jobs:
  approve:
    name: Auto-approve
    runs-on: ubuntu-22.04
    if: github.event.pull_request.user.login == 'demoability-dt-bot'
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
