name: build-and-push

on:
  workflow_call:
    inputs:
      push:
        description: Should the chart be pushed
        default: false
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: "^3.18"
      - name: Test if chart builds
        run: helm template astroshop charts/opentelemetry-demo -f config/helm-values/test.yaml

  validate-version:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auth gcloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCLOUD_SA }}"
      - name: Set up sdk
        uses: google-github-actions/setup-gcloud@v2
      - name: Verify the version
        run: ./internal/verify-chart-version

  # publish-chart:
  #   runs-on: ubuntu-24.04
  #   needs:
  #     - test
  #     - validate-version
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install helm
  #       uses: azure/setup-helm@v4.3.0
  #       with:
  #         version: "^3.18"
