name: "Image lambda deployment"
env:
  TF_VERSION: 1.13.4
  NODE_VERSION: "24.11.0"
  LAMBDA_TAG: "[AWS]git-repository:https://github.com/Dynatrace/opentelemetry-demo-gitops"
  LAMBDA_TYPE: "cloud:aws:lambda"
on:
  push:
    branches: [main, debug]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        dir: [image-provider]
        env: [live3gen]
        include:         
          - env: live3gen
            dt_url_secret: "DT_URL_LIVE3GEN"
            dt_token_secret: "DT_TOKEN_LIVE3GEN"
    defaults:
      run:
        shell: bash
    steps:
      - name: Git checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 2

      - name: Send events to Dynatrace
        uses: dczupryn-dt/dynatrace-github-action@fix-no-events-injected
        with:
          url: ${{ secrets[matrix.dt_url_secret] }}
          token: ${{ secrets[matrix.dt_token_secret] }}
          events: |
            - title: Github Actions for ${{ github.workflow }}
              type: CUSTOM_DEPLOYMENT
              entitySelector: type(SERVICE), fromRelationships.runsOn(type(${{env.LAMBDA_TYPE}}), tag(${{env.LAMBDA_TAG}}))
              properties:
                source: GitHub
                event.description: Image processing problem trigger from [PR](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
                github.repository: ${{ github.repository }}
                github.ref: ${{ github.ref }}
                github.event_name: ${{ github.event_name }}
                github.commit: ${{ github.sha }}
                terraform.outcome: "no changes - skipping deployment"
