name: Release

on:
  push:
    branches:
      - main
    paths:
      - charts/*

jobs:
  validate-pr:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      push: true
    secrets: inherit
